import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

RAW_DATA_DIR = "data/raw"
REPORT_DIR = "outputs/reports"

VECTORSTORE_DIR = "data/vectorstore"

EMBEDDING_CANDIDATES = [
    "BAAI/bge-m3",
    "BAAI/bge-large-en-v1.5",
]

WEB_MIN_DOMAIN_COUNT = 3
WEB_RECENCY_RATIO_THRESHOLD = 0.7

VALIDATION_CREDIBILITY_THRESHOLD = 0.7
VALIDATION_CONSISTENCY_THRESHOLD = 0.7
WEB_FACT_OVERLAP_THRESHOLD = 0.6
WEB_CONTRADICTION_THRESHOLD = 0.2

ANALYSIS_COVERAGE_THRESHOLD = 0.8
ANALYSIS_MIN_COMPANIES = 3
ANALYSIS_MIN_THREATS = 2
ANALYSIS_MIN_DIFFERENTIATORS = 2
ANALYSIS_MIN_IMPLICATIONS = 3

TRL_CONFIDENCE_THRESHOLD = 0.65
TRL_MIN_EVIDENCE_TYPE_COUNT = 2
TRL_MIN_CITATION_COUNT = 2

REPORT_MIN_CITATION_COUNT = 5
REPORT_COMPLETENESS_THRESHOLD = 0.9

# Query Planning
QUERY_MIN_COUNT = 5
QUERY_COVERAGE_THRESHOLD = 0.8
